FROM node:20-alpine AS builder
RUN npm install -g pnpm
WORKDIR /app

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY client/package.json ./client/

RUN pnpm install --filter client
COPY ./client ./client
EXPOSE 5173
CMD ["pnpm", "--filter", "client", "run", "dev"]